version: "2"
services:



  # WEB-SERVER
  nginx:
    build: ./nginx_dockerfile/
    ports:
        - 8000:80
    links:
        - php
    volumes_from:
        - app-volume
    container_name: nginx-webserver-container




  # PHP language
  php:
    build: ./php_dockerfile/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app-volume
    container_name: php-container



  # app- volumes
  app-volume:
    image: php:7.0-fpm
    volumes:
        - .:/usr/share/nginx/html
    command: "true"



  # mysql
  mysql:
    image: mysql:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project
    container_name: mysql-container



  # acess container mysql
  # docker exec -it CONTAINER_ID /bin/bash

  # mysql storage volume
  data:
    image: mysql:latest
    volumes:
        - /var/lib/mysql
    command: "true"



  #phpadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 7000:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
    container_name: phpmyadmin-container
